### ISSUE TITLE
#TK31 - Diseñar la autenticación con Auth o JWT.

### ISSUE THREAD

**Issue by cosmarian** [G10-ISPC/Frontend-Mobile#40]
Plan paso a paso:

1) Interfaz de Login: Crear una interfaz de usuario donde el usuario introduzca su email y contraseña.
2) API Request: Configurar una conexión desde Android hacia el servidor, enviando las credenciales del usuario.
3) Obtener JWT del servidor: Si las credenciales son correctas, el servidor devuelve un token JWT.
4) Almacenar JWT: Guardar el token en un almacenamiento seguro en el dispositivo.
5) Enviar JWT en las peticiones: Para acceder a las áreas protegidas de la aplicación, enviar el JWT en los encabezados de las peticiones.

Requisitos:

A) Retrofit para hacer solicitudes HTTP.
B) Secure Preferences o un método seguro para almacenar el JWT.
C) Servidor que proporcione autenticación JWT.

**Comment by Noobuyer** [comment]
Completado, próximo a pushear
